/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_system_WRAP_H_
#define SWIG_system_WRAP_H_

#include <map>
#include <string>


class SwigDirector_SystemApplication : public Seiscomp::System::Application, public Swig::Director {

public:
    SwigDirector_SystemApplication(PyObject *self,int argc,char **argv);
    virtual char const *className() const;
    virtual Seiscomp::Core::RTTI const &typeInfo() const;
    virtual void serialize(Seiscomp::Core::BaseObject::Archive &arg0);
    virtual Seiscomp::Core::MetaObject const *meta() const;
    virtual ~SwigDirector_SystemApplication();
    virtual Seiscomp::Core::BaseObject *clone() const;
    virtual void handleInterrupt(int arg0);
    virtual void handleInterruptSwigPublic(int arg0) {
      Seiscomp::System::Application::handleInterrupt(arg0);
    }
    virtual void printUsage() const;
    virtual char const *version();
    virtual void createBaseCommandLineDescription();
    virtual void createBaseCommandLineDescriptionSwigPublic() {
      Seiscomp::System::Application::createBaseCommandLineDescription();
    }
    virtual void createCommandLineDescription();
    virtual void createCommandLineDescriptionSwigPublic() {
      Seiscomp::System::Application::createCommandLineDescription();
    }
    virtual bool handleCommandLineOptions();
    virtual bool handleCommandLineOptionsSwigPublic() {
      return Seiscomp::System::Application::handleCommandLineOptions();
    }
    virtual bool handlePreFork();
    virtual bool handlePreForkSwigPublic() {
      return Seiscomp::System::Application::handlePreFork();
    }
    virtual bool validateParameters();
    virtual bool validateParametersSwigPublic() {
      return Seiscomp::System::Application::validateParameters();
    }
    virtual bool init();
    virtual bool initSwigPublic() {
      return Seiscomp::System::Application::init();
    }
    virtual bool run();
    virtual void done();
    virtual void doneSwigPublic() {
      Seiscomp::System::Application::done();
    }
    virtual bool forkProcess();
    virtual bool forkProcessSwigPublic() {
      return Seiscomp::System::Application::forkProcess();
    }
    virtual bool initConfiguration();
    virtual bool initConfigurationSwigPublic() {
      return Seiscomp::System::Application::initConfiguration();
    }
    virtual bool initPlugins();
    virtual bool initPluginsSwigPublic() {
      return Seiscomp::System::Application::initPlugins();
    }
    virtual void printVersion();
    virtual void printVersionSwigPublic() {
      Seiscomp::System::Application::printVersion();
    }
    virtual void printConfigVariables();
    virtual void printConfigVariablesSwigPublic() {
      Seiscomp::System::Application::printConfigVariables();
    }
    virtual void schemaValidationNames(std::vector< std::string,std::allocator< std::string > > &modules,std::vector< std::string,std::allocator< std::string > > &plugins) const;
    virtual void schemaValidationNamesSwigPublic(std::vector< std::string,std::allocator< std::string > > &modules,std::vector< std::string,std::allocator< std::string > > &plugins) const {
      Seiscomp::System::Application::schemaValidationNames(modules,plugins);
    }
    virtual bool validateSchemaParameters();
    virtual bool validateSchemaParametersSwigPublic() {
      return Seiscomp::System::Application::validateSchemaParameters();
    }
    virtual bool handleInitializationError(int stage);
    virtual bool handleInitializationErrorSwigPublic(int stage) {
      return Seiscomp::System::Application::handleInitializationError(stage);
    }
    virtual void showMessage(char const *arg0);
    virtual void showMessageSwigPublic(char const *arg0) {
      Seiscomp::System::Application::showMessage(arg0);
    }
    virtual void showWarning(char const *arg0);
    virtual void showWarningSwigPublic(char const *arg0) {
      Seiscomp::System::Application::showWarning(arg0);
    }

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class SystemApplication doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[25];
#endif

};


#endif
